//
// DO NOT EDIT THIS FILE, IT HAS BEEN GENERATED USING AndroidAnnotations.
//


package com.neteast.videotv.fragment;

import android.os.Bundle;
import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.LinearLayout;
import com.neteast.videotv.R.layout;

public final class ChoiceByMonthDialog_
    extends ChoiceByMonthDialog
{

    private View contentView_;

    private void init_(Bundle savedInstanceState) {
    }

    @Override
    public void onCreate(Bundle savedInstanceState) {
        init_(savedInstanceState);
        super.onCreate(savedInstanceState);
    }

    private void afterSetContentView_() {
        mLeftPanel = ((LinearLayout) findViewById(com.neteast.videotv.R.id.month_left_panel));
        mRightPanel = ((LinearLayout) findViewById(com.neteast.videotv.R.id.month_right_panel));
        mMonthContainer = ((LinearLayout) findViewById(com.neteast.videotv.R.id.month_container));
        ininUI();
    }

    @Override
    public View onCreateView(LayoutInflater inflater, ViewGroup container, Bundle savedInstanceState) {
        contentView_ = super.onCreateView(inflater, container, savedInstanceState);
        if (contentView_ == null) {
            contentView_ = inflater.inflate(layout.frag_choice_by_month, container, false);
        }
        afterSetContentView_();
        return contentView_;
    }

    public View findViewById(int id) {
        if (contentView_ == null) {
            return null;
        }
        return contentView_.findViewById(id);
    }

    public static ChoiceByMonthDialog_.FragmentBuilder_ builder() {
        return new ChoiceByMonthDialog_.FragmentBuilder_();
    }

    public static class FragmentBuilder_ {

        private Bundle args_;

        private FragmentBuilder_() {
            args_ = new Bundle();
        }

        public ChoiceByMonthDialog build() {
            ChoiceByMonthDialog_ fragment_ = new ChoiceByMonthDialog_();
            fragment_.setArguments(args_);
            return fragment_;
        }

    }

}
