//
// DO NOT EDIT THIS FILE, IT HAS BEEN GENERATED USING AndroidAnnotations.
//


package com.neteast.videotv.ui;

import android.app.Activity;
import android.content.Context;
import android.content.Intent;
import android.os.Bundle;
import android.view.KeyEvent;
import android.view.View;
import android.view.View.OnClickListener;
import android.view.ViewGroup.LayoutParams;
import android.widget.Button;
import android.widget.GridLayout;
import android.widget.ScrollView;
import android.widget.TextView;
import com.googlecode.androidannotations.api.SdkVersionHelper;
import com.neteast.videotv.R.id;
import com.neteast.videotv.R.layout;

public final class ResetChannelActivity_
    extends ResetChannelActivity
{


    @Override
    public void onCreate(Bundle savedInstanceState) {
        init_(savedInstanceState);
        super.onCreate(savedInstanceState);
        setContentView(layout.activity_reset_channel);
    }

    private void init_(Bundle savedInstanceState) {
    }

    private void afterSetContentView_() {
        mChannel2 = ((TextView) findViewById(id.channel2));
        mChannel1 = ((TextView) findViewById(id.channel1));
        mChannelScroll = ((ScrollView) findViewById(id.channelScroll));
        mBtnOk = ((Button) findViewById(id.btnOk));
        mChannelGrid = ((GridLayout) findViewById(id.channelGrid));
        {
            View view = findViewById(id.btnOk);
            if (view!= null) {
                view.setOnClickListener(new OnClickListener() {


                    @Override
                    public void onClick(View view) {
                        ResetChannelActivity_.this.swapChannel();
                    }

                }
                );
            }
        }
        {
            View view = findViewById(id.btnClear);
            if (view!= null) {
                view.setOnClickListener(new OnClickListener() {


                    @Override
                    public void onClick(View view) {
                        ResetChannelActivity_.this.clearChannelInput();
                    }

                }
                );
            }
        }
        {
            View view = findViewById(id.btnDefault);
            if (view!= null) {
                view.setOnClickListener(new OnClickListener() {


                    @Override
                    public void onClick(View view) {
                        ResetChannelActivity_.this.setChannelIndexToDefault();
                    }

                }
                );
            }
        }
        initUI();
    }

    @Override
    public void setContentView(int layoutResID) {
        super.setContentView(layoutResID);
        afterSetContentView_();
    }

    @Override
    public void setContentView(View view, LayoutParams params) {
        super.setContentView(view, params);
        afterSetContentView_();
    }

    @Override
    public void setContentView(View view) {
        super.setContentView(view);
        afterSetContentView_();
    }

    @Override
    public boolean onKeyDown(int keyCode, KeyEvent event) {
        if (((SdkVersionHelper.getSdkInt()< 5)&&(keyCode == KeyEvent.KEYCODE_BACK))&&(event.getRepeatCount() == 0)) {
            onBackPressed();
        }
        return super.onKeyDown(keyCode, event);
    }

    public static ResetChannelActivity_.IntentBuilder_ intent(Context context) {
        return new ResetChannelActivity_.IntentBuilder_(context);
    }

    public static class IntentBuilder_ {

        private Context context_;
        private final Intent intent_;

        public IntentBuilder_(Context context) {
            context_ = context;
            intent_ = new Intent(context, ResetChannelActivity_.class);
        }

        public Intent get() {
            return intent_;
        }

        public ResetChannelActivity_.IntentBuilder_ flags(int flags) {
            intent_.setFlags(flags);
            return this;
        }

        public void start() {
            context_.startActivity(intent_);
        }

        public void startForResult(int requestCode) {
            if (context_ instanceof Activity) {
                ((Activity) context_).startActivityForResult(intent_, requestCode);
            } else {
                context_.startActivity(intent_);
            }
        }

    }

}
