//
// DO NOT EDIT THIS FILE, IT HAS BEEN GENERATED USING AndroidAnnotations.
//


package com.neteast.videotv.ui;

import android.app.Activity;
import android.content.Context;
import android.content.Intent;
import android.os.Bundle;
import android.view.View;
import android.view.View.OnClickListener;
import android.view.ViewGroup.LayoutParams;
import android.widget.Button;
import android.widget.LinearLayout;
import android.widget.TextView;
import com.android.volley.toolbox.NetworkImageView;
import com.neteast.videotv.R.id;
import com.neteast.videotv.R.layout;

public final class VideoDetailActivity_
    extends VideoDetailActivity
{


    @Override
    public void onCreate(Bundle savedInstanceState) {
        init_(savedInstanceState);
        super.onCreate(savedInstanceState);
        setContentView(layout.activity_detail);
    }

    private void init_(Bundle savedInstanceState) {
    }

    private void afterSetContentView_() {
        mShare = ((Button) findViewById(id.detail_share));
        mDescription = ((TextView) findViewById(id.detail_description));
        mChoiceOrigin = ((Button) findViewById(id.detail_choice_origin));
        mMovieImage = ((NetworkImageView) findViewById(id.detail_movie_image));
        mChoiceSeries = ((Button) findViewById(id.detail_choice_series));
        mBaseInfo2 = ((TextView) findViewById(id.detail_movie_info2));
        mBaseInfo3 = ((TextView) findViewById(id.detail_movie_info3));
        mMoreDescription = ((Button) findViewById(id.detail_more_description));
        mCollection = ((Button) findViewById(id.detail_collection));
        mBaseInfo5 = ((TextView) findViewById(id.detail_movie_info5));
        mPlay = ((Button) findViewById(id.detail_play));
        mRecommendTitle = ((TextView) findViewById(id.detail_recommend_title));
        mMark = ((TextView) findViewById(id.detail_mark));
        mBaseInfo1 = ((TextView) findViewById(id.detail_movie_info1));
        mTitle = ((TextView) findViewById(id.detail_movie_title));
        mBaseInfo4 = ((TextView) findViewById(id.detail_movie_info4));
        mRecommendContainer = ((LinearLayout) findViewById(id.detail_recommend_container));
        mBaseInfo6 = ((TextView) findViewById(id.detail_movie_info6));
        {
            View view = findViewById(id.detail_more_description);
            if (view!= null) {
                view.setOnClickListener(new OnClickListener() {


                    @Override
                    public void onClick(View view) {
                        VideoDetailActivity_.this.showMoreDescription();
                    }

                }
                );
            }
        }
        {
            View view = findViewById(id.detail_choice_origin);
            if (view!= null) {
                view.setOnClickListener(new OnClickListener() {


                    @Override
                    public void onClick(View view) {
                        VideoDetailActivity_.this.choiceOrigin();
                    }

                }
                );
            }
        }
        {
            View view = findViewById(id.detail_play);
            if (view!= null) {
                view.setOnClickListener(new OnClickListener() {


                    @Override
                    public void onClick(View view) {
                        VideoDetailActivity_.this.play();
                    }

                }
                );
            }
        }
        {
            View view = findViewById(id.detail_collection);
            if (view!= null) {
                view.setOnClickListener(new OnClickListener() {


                    @Override
                    public void onClick(View view) {
                        VideoDetailActivity_.this.collect();
                    }

                }
                );
            }
        }
        {
            View view = findViewById(id.detail_choice_series);
            if (view!= null) {
                view.setOnClickListener(new OnClickListener() {


                    @Override
                    public void onClick(View view) {
                        VideoDetailActivity_.this.choiceSeries();
                    }

                }
                );
            }
        }
        parpareViews();
    }

    @Override
    public void setContentView(int layoutResID) {
        super.setContentView(layoutResID);
        afterSetContentView_();
    }

    @Override
    public void setContentView(View view, LayoutParams params) {
        super.setContentView(view, params);
        afterSetContentView_();
    }

    @Override
    public void setContentView(View view) {
        super.setContentView(view);
        afterSetContentView_();
    }

    public static VideoDetailActivity_.IntentBuilder_ intent(Context context) {
        return new VideoDetailActivity_.IntentBuilder_(context);
    }

    public static class IntentBuilder_ {

        private Context context_;
        private final Intent intent_;

        public IntentBuilder_(Context context) {
            context_ = context;
            intent_ = new Intent(context, VideoDetailActivity_.class);
        }

        public Intent get() {
            return intent_;
        }

        public VideoDetailActivity_.IntentBuilder_ flags(int flags) {
            intent_.setFlags(flags);
            return this;
        }

        public void start() {
            context_.startActivity(intent_);
        }

        public void startForResult(int requestCode) {
            if (context_ instanceof Activity) {
                ((Activity) context_).startActivityForResult(intent_, requestCode);
            } else {
                context_.startActivity(intent_);
            }
        }

    }

}
