//
// DO NOT EDIT THIS FILE, IT HAS BEEN GENERATED USING AndroidAnnotations.
//


package com.neteast.videotv.fragment;

import android.os.Bundle;
import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.HorizontalScrollView;
import com.neteast.videotv.R.layout;
import com.neteast.videotv.ui.widget.FocusText;
import com.neteast.videotv.ui.widget.PosterView;

public final class HomePageFragment_
    extends HomePageFragment
{

    private View contentView_;

    private void init_(Bundle savedInstanceState) {
    }

    @Override
    public void onCreate(Bundle savedInstanceState) {
        init_(savedInstanceState);
        super.onCreate(savedInstanceState);
    }

    private void afterSetContentView_() {
        image1_5 = ((PosterView) findViewById(com.neteast.videotv.R.id.homepage_1_5));
        image3_8 = ((PosterView) findViewById(com.neteast.videotv.R.id.homepage_3_8));
        image1_4 = ((PosterView) findViewById(com.neteast.videotv.R.id.homepage_1_4));
        image1_7 = ((PosterView) findViewById(com.neteast.videotv.R.id.homepage_1_7));
        image3_4 = ((PosterView) findViewById(com.neteast.videotv.R.id.homepage_3_4));
        image1_6 = ((PosterView) findViewById(com.neteast.videotv.R.id.homepage_1_6));
        image1_2 = ((FocusText) findViewById(com.neteast.videotv.R.id.homepage_1_2));
        mScroll = ((HorizontalScrollView) findViewById(com.neteast.videotv.R.id.scroll));
        image2_5 = ((FocusText) findViewById(com.neteast.videotv.R.id.homepage_2_5));
        image3_1 = ((PosterView) findViewById(com.neteast.videotv.R.id.homepage_3_1));
        image3_3 = ((PosterView) findViewById(com.neteast.videotv.R.id.homepage_3_3));
        image2_2 = ((PosterView) findViewById(com.neteast.videotv.R.id.homepage_2_2));
        image2_1 = ((PosterView) findViewById(com.neteast.videotv.R.id.homepage_2_1));
        image2_4 = ((PosterView) findViewById(com.neteast.videotv.R.id.homepage_2_4));
        image3_5 = ((PosterView) findViewById(com.neteast.videotv.R.id.homepage_3_5));
        image1_1 = ((PosterView) findViewById(com.neteast.videotv.R.id.homepage_1_1));
        image2_6 = ((PosterView) findViewById(com.neteast.videotv.R.id.homepage_2_6));
        image2_3 = ((FocusText) findViewById(com.neteast.videotv.R.id.homepage_2_3));
        image3_10 = ((PosterView) findViewById(com.neteast.videotv.R.id.homepage_3_10));
        image3_9 = ((PosterView) findViewById(com.neteast.videotv.R.id.homepage_3_9));
        image3_7 = ((PosterView) findViewById(com.neteast.videotv.R.id.homepage_3_7));
        image1_3 = ((FocusText) findViewById(com.neteast.videotv.R.id.homepage_1_3));
        image3_6 = ((FocusText) findViewById(com.neteast.videotv.R.id.homepage_3_6));
        image3_2 = ((FocusText) findViewById(com.neteast.videotv.R.id.homepage_3_2));
        initAnimation();
    }

    @Override
    public View onCreateView(LayoutInflater inflater, ViewGroup container, Bundle savedInstanceState) {
        contentView_ = super.onCreateView(inflater, container, savedInstanceState);
        if (contentView_ == null) {
            contentView_ = inflater.inflate(layout.frag_homepage, container, false);
        }
        afterSetContentView_();
        return contentView_;
    }

    public View findViewById(int id) {
        if (contentView_ == null) {
            return null;
        }
        return contentView_.findViewById(id);
    }

    public static HomePageFragment_.FragmentBuilder_ builder() {
        return new HomePageFragment_.FragmentBuilder_();
    }

    public static class FragmentBuilder_ {

        private Bundle args_;

        private FragmentBuilder_() {
            args_ = new Bundle();
        }

        public HomePageFragment build() {
            HomePageFragment_ fragment_ = new HomePageFragment_();
            fragment_.setArguments(args_);
            return fragment_;
        }

    }

}
